// ─── Seed Data ───────────────────────────────────────────────────────────────
// This file is the single source of truth for demo data in MOCK MODE.
// All products have:  salesCount (for Best Sellers sort), frequentlyBoughtWith (FBT slugs),
//                     dietaryType, spiceLevel, and a full nutrition block.
// No product has price ≤ 0 or a missing required field.
// ─────────────────────────────────────────────────────────────────────────────

const products = [
  // ── Snacks & Namkeen ──────────────────────────────────────────────────────
  {
    name: "Beetroot Chips",
    slug: "beetroot-chips",
    tagline: "Beetroot, Crispy, Nutritious Treat",
    category: "Snacks and Namkeen",
    price: 70,
    weight: "150g",
    image: "/images/product-snack.png",
    tags: ["Healthy", "Vegan", "Gluten-Free"],
    spiceLevel: "None",
    dietaryType: "Vegan",
    description:
      "Thin-sliced beetroot, sun-dried and slow-fried in small batches until crisp. Lightly salted, no added colour — the deep red is all beetroot.",
    nutrition: {
      servingSize: "30g",
      calories: 145,
      protein: "1.2g",
      carbs: "16g",
      fat: "8g",
      ingredients: "Beetroot, groundnut oil, rock salt.",
      allergens: "None. Processed in a facility that also handles peanuts.",
      shelfLife: "4 months from packaging date.",
      storageInstructions: "Store in a cool, dry place away from direct sunlight. Reseal after opening.",
    },
    salesCount: 198,
    frequentlyBoughtWith: ["corn-chakali", "jwari-bhel", "cheeseling"],
    reviews: [
      { name: "Anjali Deshmukh", rating: 5, comment: "Crunchy and not overly oily — my kids actually prefer this to potato chips now.", verifiedPurchase: true },
      { name: "Sanket P.", rating: 4, comment: "Good taste but the pack could be a bit bigger for the price.", verifiedPurchase: true },
    ],
    linkedRecipeSlug: "healthy-tea-time-snacks",
  },
  {
    name: "Cheeseling",
    slug: "cheeseling",
    tagline: "Cheesy, Crispy, Snack Time",
    category: "Snacks and Namkeen",
    price: 110,
    weight: "200g",
    image: "/images/product-snack.png",
    tags: ["Kids Favourite"],
    spiceLevel: "Mild",
    dietaryType: "Veg",
    description:
      "Crisp, baked cheese sticks with a sharp cheddar bite — a tea-time favourite that holds its crunch for weeks.",
    nutrition: {
      servingSize: "25g",
      calories: 130,
      protein: "3g",
      carbs: "14g",
      fat: "7g",
      ingredients: "Refined wheat flour, cheese powder, edible vegetable oil, salt, raising agent.",
      allergens: "Contains milk and wheat (gluten).",
      shelfLife: "3 months from packaging date.",
      storageInstructions: "Store in a cool, dry place. Consume within 3 days of opening.",
    },
    salesCount: 287,
    frequentlyBoughtWith: ["beetroot-chips", "corn-chakali", "tangy-tomato"],
    reviews: [
      { name: "Priyanka Naik", rating: 5, comment: "Genuinely cheesy, not just artificial flavour. Great with evening chai.", verifiedPurchase: true },
      { name: "Rahul V.", rating: 4, comment: "My kids love this. Would buy again.", verifiedPurchase: false },
    ],
    linkedRecipeSlug: null,
  },
  {
    name: "Corn Chakali",
    slug: "corn-chakali",
    tagline: "Crispy, Golden, Corn Crunch",
    category: "Snacks and Namkeen",
    price: 50,
    weight: "150g",
    image: "/images/product-snack.png",
    tags: ["Traditional"],
    spiceLevel: "Medium",
    dietaryType: "Veg",
    description:
      "A corn-flour twist on the classic Maharashtrian chakli — spiral-shaped, deep-fried, seasoned with cumin and red chilli.",
    nutrition: {
      servingSize: "30g",
      calories: 150,
      protein: "2g",
      carbs: "18g",
      fat: "8g",
      ingredients: "Corn flour, rice flour, edible oil, cumin, red chilli powder, salt, asafoetida.",
      allergens: "None.",
      shelfLife: "3 months from packaging date.",
      storageInstructions: "Store in a cool, dry place. Reseal after opening.",
    },
    salesCount: 312,
    frequentlyBoughtWith: ["jwari-bhel", "beetroot-chips", "aam-ka-achaar"],
    reviews: [
      { name: "Ramesh Kulkarni", rating: 4, comment: "Tastes like the chakli my aaji used to make. A little more salt would be perfect.", verifiedPurchase: true },
      { name: "Sunita More", rating: 5, comment: "Perfectly crispy. Great with tea!", verifiedPurchase: true },
    ],
    linkedRecipeSlug: "healthy-tea-time-snacks",
  },
  {
    name: "Thepla Puri",
    slug: "thepla-puri",
    tagline: "Authentic, Rustic, Gujarati Flavor",
    category: "Snacks and Namkeen",
    price: 90,
    weight: "200g",
    image: "/images/product-snack.png",
    tags: ["Traditional"],
    spiceLevel: "Mild",
    dietaryType: "Veg",
    description:
      "Crisp fried puris seasoned with methi and mild spice, inspired by Gujarati thepla but made shelf-stable for snacking.",
    nutrition: {
      servingSize: "30g",
      calories: 140,
      protein: "2.5g",
      carbs: "15g",
      fat: "7.5g",
      ingredients: "Wheat flour, fenugreek leaves, edible oil, turmeric, chilli powder, salt.",
      allergens: "Contains wheat (gluten).",
      shelfLife: "2.5 months from packaging date.",
      storageInstructions: "Store in a cool, dry place. Best consumed within a week of opening.",
    },
    salesCount: 98,
    frequentlyBoughtWith: ["aam-ka-achaar", "lasun-loncha", "mishrit-loncha"],
    reviews: [
      { name: "Geeta Patel", rating: 5, comment: "Exactly the right amount of methi flavor. Great with chai or achaar.", verifiedPurchase: true },
    ],
    linkedRecipeSlug: null,
  },
  {
    name: "Jwari Bhel",
    slug: "jwari-bhel",
    tagline: "Authentic, Crispy, Goodness",
    category: "Snacks and Namkeen",
    price: 30,
    weight: "100g",
    image: "/images/product-snack.png",
    tags: ["Healthy", "Gluten-Free"],
    spiceLevel: "Medium",
    dietaryType: "Veg",
    description: "Puffed jowar mixed with peanuts, sev, and a tangy-spicy seasoning — a light, gluten-free take on bhel.",
    nutrition: {
      servingSize: "40g",
      calories: 160,
      protein: "3g",
      carbs: "20g",
      fat: "7g",
      ingredients: "Puffed jowar, peanuts, sev (gram flour), spices, salt, edible oil.",
      allergens: "Contains gram flour (may contain traces of gluten from shared lines) and peanuts.",
      shelfLife: "2 months from packaging date.",
      storageInstructions: "Store in a cool, dry, airtight container.",
    },
    salesCount: 265,
    frequentlyBoughtWith: ["corn-chakali", "beetroot-chips", "aam-ka-achaar"],
    reviews: [
      { name: "Meera Joshi", rating: 5, comment: "Light snack, good for evening hunger pangs without feeling heavy.", verifiedPurchase: true },
      { name: "Kavita M.", rating: 4, comment: "Love the jowar crunch! Great healthy option.", verifiedPurchase: true },
    ],
    linkedRecipeSlug: null,
  },
  {
    name: "Tangy Tomato Rings",
    slug: "tangy-tomato",
    tagline: "Crunchy, Tangy, Tomato Rings",
    category: "Snacks and Namkeen",
    price: 100,
    weight: "150g",
    image: "/images/product-snack.png",
    tags: [],
    spiceLevel: "Medium",
    dietaryType: "Veg",
    description: "Ring-shaped extruded snacks with a tangy tomato coating — a crunchy, moreish everyday munch.",
    nutrition: {
      servingSize: "25g",
      calories: 120,
      protein: "1.5g",
      carbs: "16g",
      fat: "5.5g",
      ingredients: "Corn meal, edible oil, tomato powder, sugar, salt, spices.",
      allergens: "None.",
      shelfLife: "4 months from packaging date.",
      storageInstructions: "Store in a cool, dry place. Reseal after opening.",
    },
    salesCount: 119,
    frequentlyBoughtWith: ["cheeseling", "corn-chakali", "jwari-bhel"],
    reviews: [
      { name: "Rohit S.", rating: 4, comment: "Nice tangy flavor. Good value for money.", verifiedPurchase: true },
    ],
    linkedRecipeSlug: null,
  },

  // ── Pickles & Condiments ──────────────────────────────────────────────────
  {
    name: "Aam Ka Achaar (Mango Pickle)",
    slug: "aam-ka-achaar",
    tagline: "Sun-dried, Tangy, Traditional Mango Pickle",
    category: "Pickles & Condiments",
    price: 220,
    weight: "300g",
    image: "/images/product-pickle.png",
    tags: ["Traditional", "Preservative-Free", "Bestseller"],
    spiceLevel: "Medium",
    dietaryType: "Veg",
    description:
      "Sun-dried raw mango pieces slow-marinated in mustard oil with hand-ground spices — a Maharashtrian pantry essential. Made in small batches without artificial preservatives, just as it has been for generations. The perfect companion to dal-rice, rotis, and parathas.",
    nutrition: {
      servingSize: "15g",
      calories: 45,
      protein: "0.3g",
      carbs: "3g",
      fat: "3.5g",
      ingredients: "Raw mango, mustard oil, red chilli, mustard seeds, fenugreek seeds, turmeric, asafoetida, salt.",
      allergens: "Contains mustard. Free from other common allergens.",
      shelfLife: "12 months from packaging date. Refrigerate after opening and consume within 60 days.",
      storageInstructions: "Store in a cool, dry place away from sunlight. Always use a dry spoon.",
    },
    salesCount: 380,
    frequentlyBoughtWith: ["lasun-loncha", "mishrit-loncha", "corn-chakali"],
    reviews: [
      { name: "Meghna Kulkarni", rating: 5, comment: "The best achaar I've had outside of my grandmother's kitchen. The mango pieces are thick and perfectly pickled.", verifiedPurchase: true },
      { name: "Rohan Desai", rating: 5, comment: "Ordered this for the first time and immediately reordered. Goes perfectly with dal-rice or even parathas.", verifiedPurchase: true },
      { name: "Shalini P.", rating: 4, comment: "Authentic taste, not too oily. Would love a larger pack option.", verifiedPurchase: true },
      { name: "Aditya Naik", rating: 5, comment: "This is what a real mango pickle should taste like. No artificial flavors, just pure achaar.", verifiedPurchase: false },
      { name: "Priya Joshi", rating: 4, comment: "Great quality. The spice level is perfect — not too hot, not too mild.", verifiedPurchase: true },
    ],
    linkedRecipeSlug: "konkan-pickle-rice-bowl",
  },
  {
    name: "Lasun Loncha (Garlic Pickle)",
    slug: "lasun-loncha",
    tagline: "Bold, Garlicky, Fiery Konkan Pickle",
    category: "Pickles & Condiments",
    price: 180,
    weight: "200g",
    image: "/images/product-pickle.png",
    tags: ["Traditional", "Preservative-Free"],
    spiceLevel: "Spicy",
    dietaryType: "Veg",
    description:
      "Whole garlic cloves marinated in a fiery red-chilli and mustard oil masala — a beloved Konkan condiment that adds instant depth to any meal. The bold garlic punch makes it irresistible with bhakri and dal.",
    nutrition: {
      servingSize: "10g",
      calories: 38,
      protein: "0.8g",
      carbs: "2.5g",
      fat: "3g",
      ingredients: "Garlic, mustard oil, red chilli, vinegar, cumin, salt, asafoetida.",
      allergens: "Contains mustard.",
      shelfLife: "10 months from packaging date. Refrigerate after opening.",
      storageInstructions: "Store in a cool, dry place. Use a clean, dry spoon always.",
    },
    salesCount: 224,
    frequentlyBoughtWith: ["aam-ka-achaar", "mishrit-loncha", "thepla-puri"],
    reviews: [
      { name: "Vinita Shinde", rating: 5, comment: "Absolutely fiery and addictive. A must-have with bhakri and dal.", verifiedPurchase: true },
      { name: "Kunal More", rating: 4, comment: "Real garlic flavour, not the artificial kind. Very satisfying.", verifiedPurchase: true },
      { name: "Ashok T.", rating: 5, comment: "Best garlic pickle I've tried. The spice level is just right for garlic lovers.", verifiedPurchase: false },
    ],
    linkedRecipeSlug: "konkan-pickle-rice-bowl",
  },
  {
    name: "Mishrit Loncha (Mixed Vegetable Pickle)",
    slug: "mishrit-loncha",
    tagline: "Six Vegetables, One Classic Pickle",
    category: "Pickles & Condiments",
    price: 160,
    weight: "250g",
    image: "/images/product-pickle.png",
    tags: ["Traditional", "Preservative-Free", "Healthy"],
    spiceLevel: "Medium",
    dietaryType: "Veg",
    description:
      "A colorful medley of six seasonal vegetables — raw mango, carrot, cauliflower, ginger, chilli, and lemon — slow-pickled in Naik Foods' signature masala. A versatile accompaniment to any Indian meal.",
    nutrition: {
      servingSize: "15g",
      calories: 40,
      protein: "0.4g",
      carbs: "3g",
      fat: "3g",
      ingredients: "Raw mango, carrot, cauliflower, ginger, green chilli, lemon, mustard oil, spices, salt.",
      allergens: "Contains mustard.",
      shelfLife: "9 months from packaging date. Refrigerate after opening.",
      storageInstructions: "Store away from sunlight. Always use a dry spoon.",
    },
    salesCount: 176,
    frequentlyBoughtWith: ["aam-ka-achaar", "lasun-loncha", "thepla-puri"],
    reviews: [
      { name: "Ananya Gokhale", rating: 5, comment: "Love the variety of vegetables in this. Each bite is different. Great value.", verifiedPurchase: true },
      { name: "Suresh B.", rating: 4, comment: "Good balance of spice and tang. Perfect side for rice.", verifiedPurchase: true },
    ],
    linkedRecipeSlug: null,
  },
  {
    name: "Ambadi Bhajiche Lonche",
    slug: "ambadi-bhajiche-lonche",
    tagline: "Traditional, Tangy Pickle Delight",
    category: "Pickles & Condiments",
    price: 190,
    weight: "250g",
    image: "/images/product-pickle.png",
    tags: ["Traditional", "Preservative-Free"],
    spiceLevel: "Spicy",
    dietaryType: "Veg",
    description:
      "Sun-dried ambadi (roselle) leaves pickled in mustard oil with a hand-ground Konkan-style masala — tangy, spicy, no added preservatives.",
    nutrition: {
      servingSize: "10g",
      calories: 35,
      protein: "0.3g",
      carbs: "2g",
      fat: "3g",
      ingredients: "Ambadi leaves, mustard oil, red chilli, mustard seeds, fenugreek, salt, vinegar.",
      allergens: "Contains mustard.",
      shelfLife: "12 months from packaging date, refrigerate after opening.",
      storageInstructions: "Store in a cool, dry place. Refrigerate after opening and use a dry spoon.",
    },
    salesCount: 243,
    frequentlyBoughtWith: ["aam-ka-achaar", "kolambi-lonche", "thepla-puri"],
    reviews: [
      { name: "Sujata Naik", rating: 5, comment: "Exactly like the ambadi lonche my grandmother made in Konkan. Real deal.", verifiedPurchase: true },
      { name: "Ajit R.", rating: 4, comment: "Quite spicy, so go easy the first time. Flavour is authentic.", verifiedPurchase: true },
    ],
    linkedRecipeSlug: null,
  },
  {
    name: "Prawns Pickle (Kolambi Lonche)",
    slug: "kolambi-lonche",
    tagline: "Authentic, Spicy, Coastal Flavor",
    category: "Pickles & Condiments",
    price: 280,
    weight: "200g",
    image: "/images/product-pickle.png",
    tags: ["Non-Vegetarian", "Coastal"],
    spiceLevel: "Spicy",
    dietaryType: "Non-Veg",
    description: "A Konkan coastal specialty — sun-dried prawns pickled in a fiery, tangy masala with mustard oil.",
    nutrition: {
      servingSize: "15g",
      calories: 55,
      protein: "3.5g",
      carbs: "1.5g",
      fat: "4g",
      ingredients: "Prawns, mustard oil, red chilli, tamarind, garlic, spices, salt.",
      allergens: "Contains shellfish and mustard.",
      shelfLife: "6 months refrigerated; consume within 30 days of opening.",
      storageInstructions: "Always refrigerate. Use a dry, clean spoon to avoid contamination.",
    },
    salesCount: 156,
    frequentlyBoughtWith: ["ambadi-bhajiche-lonche", "aam-ka-achaar", "thepla-puri"],
    reviews: [
      { name: "Vinod Sawant", rating: 5, comment: "Strong, authentic coastal flavour. A little goes a long way with rice.", verifiedPurchase: true },
      { name: "Deepa K.", rating: 4, comment: "Exactly what I was looking for — real Konkan kolambi taste.", verifiedPurchase: false },
    ],
    linkedRecipeSlug: null,
  },

  // ── Dry / Instant Grocery ─────────────────────────────────────────────────
  {
    name: "Methi Thalipith Bhajni",
    slug: "methi-thalipith-bhajni",
    tagline: "Traditional, Healthy, Flavor",
    category: "Dry/Instant Grocery",
    price: 70,
    weight: "500g",
    image: "/images/product-grocery.png",
    tags: ["Healthy", "Traditional"],
    spiceLevel: "None",
    dietaryType: "Veg",
    description:
      "A ready-mix multigrain bhajni flour with fenugreek leaves — just add water, onion, and spices for authentic thalipith in minutes.",
    nutrition: {
      servingSize: "50g (dry)",
      calories: 180,
      protein: "6g",
      carbs: "32g",
      fat: "3g",
      ingredients: "Jowar, bajra, rice, chana dal, urad dal, coriander seeds, dried fenugreek leaves, spices.",
      allergens: "None.",
      shelfLife: "6 months from packaging date.",
      storageInstructions: "Store in a cool, dry, airtight container.",
    },
    salesCount: 87,
    frequentlyBoughtWith: ["aam-ka-achaar", "lasun-loncha", "shahi-mukhwas"],
    reviews: [
      { name: "Sonal Patil", rating: 5, comment: "Saves so much time — tastes like homemade bhajni, not a shortcut mix.", verifiedPurchase: true },
      { name: "Nandita R.", rating: 4, comment: "Good quality grains. Makes soft and tasty thalipith.", verifiedPurchase: true },
    ],
    linkedRecipeSlug: "quick-thalipith-breakfast",
  },
  {
    name: "Multi Millet Noodles",
    slug: "multi-millet-noodles",
    tagline: "Millet Goodness, Crunchy, Delight",
    category: "Dry/Instant Grocery",
    price: 100,
    weight: "180g",
    image: "/images/product-grocery.png",
    tags: ["Healthy", "Millet"],
    spiceLevel: "None",
    dietaryType: "Veg",
    description: "A blend of five millets shaped into quick-cooking noodles — a fibre-rich alternative to refined-flour noodles.",
    nutrition: {
      servingSize: "60g (dry)",
      calories: 210,
      protein: "5g",
      carbs: "40g",
      fat: "2g",
      ingredients: "Jowar, bajra, ragi, foxtail millet, little millet flour.",
      allergens: "None. Processed in a facility that also handles wheat.",
      shelfLife: "8 months from packaging date.",
      storageInstructions: "Store in a cool, dry, airtight container away from moisture.",
    },
    salesCount: 76,
    frequentlyBoughtWith: ["methi-thalipith-bhajni"],
    reviews: [
      { name: "Tanya S.", rating: 4, comment: "Great healthy alternative! My kids actually enjoyed it.", verifiedPurchase: true },
    ],
    linkedRecipeSlug: null,
  },

  // ── Mukhvas & Digestives ──────────────────────────────────────────────────
  {
    name: "Shahi Mukhwas",
    slug: "shahi-mukhwas",
    tagline: "Royal Flavor, Cool, Fresh",
    category: "Mukhvas & Digestives",
    price: 85,
    weight: "100g",
    image: "/images/product-mukhwas.png",
    tags: ["After-Meal"],
    spiceLevel: "None",
    dietaryType: "Veg",
    description: "A festive blend of candied fennel, sugar-coated seeds, and rose petals — a fragrant after-meal digestive.",
    nutrition: {
      servingSize: "10g",
      calories: 38,
      protein: "0.2g",
      carbs: "9g",
      fat: "0.1g",
      ingredients: "Fennel seeds, sugar, dried coconut, rose petals, edible colour, cardamom.",
      allergens: "Contains coconut.",
      shelfLife: "9 months from packaging date.",
      storageInstructions: "Store in a cool, dry, airtight container.",
    },
    salesCount: 134,
    frequentlyBoughtWith: ["aaswad-mitha-paan"],
    reviews: [
      { name: "Rekha M.", rating: 5, comment: "Sweet, fragrant, and perfectly fresh. Love the rose petals!", verifiedPurchase: true },
      { name: "Harish J.", rating: 4, comment: "Good mukhwas. The cardamom flavour is very refreshing.", verifiedPurchase: false },
    ],
    linkedRecipeSlug: null,
  },
  {
    name: "Aaswad Mitha Paan",
    slug: "aaswad-mitha-paan",
    tagline: "Sweet Paan, Tasty, Fresh",
    category: "Mukhvas & Digestives",
    price: 85,
    weight: "100g",
    image: "/images/product-mukhwas.png",
    tags: ["After-Meal"],
    spiceLevel: "None",
    dietaryType: "Veg",
    description:
      "A ready-to-eat sweet paan mix with gulkand, fennel, and betel leaf flakes — the classic after-meal freshener, no actual paan leaf needed.",
    nutrition: {
      servingSize: "10g",
      calories: 40,
      protein: "0.2g",
      carbs: "9.5g",
      fat: "0.2g",
      ingredients: "Fennel seeds, gulkand (rose petal preserve), betel leaf flakes, sugar, cardamom, edible colour.",
      allergens: "None.",
      shelfLife: "9 months from packaging date.",
      storageInstructions: "Store in a cool, dry, airtight container.",
    },
    salesCount: 121,
    frequentlyBoughtWith: ["shahi-mukhwas"],
    reviews: [
      { name: "Kavita Rane", rating: 4, comment: "Sweet and fragrant, good after a heavy meal. Wish the pack was resealable.", verifiedPurchase: true },
    ],
    linkedRecipeSlug: null,
  },
];

// ── Combos ────────────────────────────────────────────────────────────────────
const combos = [
  {
    name: "Konkan Pickle Sampler",
    slug: "konkan-pickle-sampler",
    description:
      "Three coastal Konkan pickles in one box — mango achaar, lasun loncha, and ambadi bhajiche lonche. Great for gifting and exploring authentic Konkan flavors.",
    image: "/images/product-pickle.png",
    productSlugs: ["aam-ka-achaar", "lasun-loncha", "ambadi-bhajiche-lonche"],
    price: 510,
    occasion: "Gifting",
  },
  {
    name: "Everyday Snack Box",
    slug: "everyday-snack-box",
    description:
      "A mix of five bestselling namkeen and snacks, perfect for the pantry or as a tea-time assortment for the whole family.",
    image: "/images/product-pickle.png",
    productSlugs: ["beetroot-chips", "cheeseling", "corn-chakali", "jwari-bhel", "tangy-tomato"],
    price: 320,
    occasion: "Everyday",
  },
  {
    name: "Naik Foods Diwali Gift Box",
    slug: "diwali-gift-box",
    description:
      "A festive assortment of traditional snacks, pickles, and digestives — thoughtfully curated for gifting during Diwali and other celebrations.",
    image: "/images/product-pickle.png",
    productSlugs: ["aam-ka-achaar", "corn-chakali", "shahi-mukhwas", "aaswad-mitha-paan", "beetroot-chips"],
    price: 480,
    occasion: "Diwali",
  },
];

// ── Stock & Price Overrides ───────────────────────────────────────────────────
// Intentionally set a few items low/zero to exercise those UI states in the demo.
const STOCK_OVERRIDES = {
  "beetroot-chips": 42,
  "cheeseling": 0,             // out of stock — demonstrates the out-of-stock UI state
  "corn-chakali": 6,           // low stock — demonstrates a low-stock warning
  "thepla-puri": 18,
  "jwari-bhel": 30,
  "aam-ka-achaar": 24,
  "lasun-loncha": 17,
  "mishrit-loncha": 20,
  "ambadi-bhajiche-lonche": 15,
  "kolambi-lonche": 9,
  "tangy-tomato": 25,
  "methi-thalipith-bhajni": 40,
  "multi-millet-noodles": 22,
  "shahi-mukhwas": 33,
  "aaswad-mitha-paan": 12,
};

const COMPARE_AT_OVERRIDES = {
  "cheeseling": 130,
  "tangy-tomato": 120,
  "aaswad-mitha-paan": 100,
  "aam-ka-achaar": 260,       // clear discount on star product
  "mishrit-loncha": 190,
};

const productsWithInventory = products.map((p) => ({
  ...p,
  stock: STOCK_OVERRIDES[p.slug] ?? 20,
  compareAtPrice: COMPARE_AT_OVERRIDES[p.slug] ?? null,
  images: [p.image],
  isActive: true,
}));

module.exports = { products: productsWithInventory, combos };
